# Generated by Django 4.1.5 on 2023-01-24 16:57

import discordlogin.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiscordGuild',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('g_id', models.BigIntegerField()),
                ('u_id', models.BigIntegerField()),
                ('name', models.CharField(max_length=100)),
                ('icon', models.CharField(max_length=150)),
            ],
            managers=[
                ('objects', discordlogin.managers.DiscordGuildManager()),
            ],
        ),
        migrations.CreateModel(
            name='DiscordUser',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('discord_tag', models.CharField(max_length=100)),
                ('avatar', models.CharField(max_length=100)),
                ('public_flags', models.IntegerField()),
                ('flags', models.IntegerField()),
                ('locale', models.CharField(max_length=100)),
                ('mfa_enabled', models.BooleanField()),
                ('last_login', models.DateTimeField(null=True)),
            ],
            managers=[
                ('objects', discordlogin.managers.DiscordOAuth2Manager()),
            ],
        ),
    ]
